# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "main" ]
    paths:
      - 'simplebank/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'simplebank/**'

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'
      id: go

    -  name: Check out code into the Go module directory 
       uses: actions/checkout@v4

    - name: Test
      run: make test
